version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: shop_db
      MYSQL_USER: shop_user
      MYSQL_PASSWORD: shop_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build:
      context: ./back
      dockerfile: Dockerfile
    container_name: shop_backend
    ports:
      - "5000:5000"
    volumes:
      - ./back:/app
      - /app/node_modules
    depends_on:
      - mysql
    environment:
      - DB_HOST=mysql
      - DB_USER=shop_user
      - DB_PASSWORD=shop_password
      - DB_NAME=shop_db
      - JWT_SECRET=your_jwt_secret

volumes:
  mysql_data: